### ISSUE TITLE
get my own anchors

### ISSUE THREAD

**Issue by Spider95** [experiencor/keras-yolo2#231]
h run get_anchors and I have this error :
runfile('D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py', wdir='D:/My Data/My Work/GP/code/CodeFinalFinal')
Reloaded modules: preprocessing, utilss
Taher1 0
(0,)
Traceback (most recent call last):

  File "<ipython-input-40-43a4c72b639b>", line 1, in <module>
    runfile('D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py', wdir='D:/My Data/My Work/GP/code/CodeFinalFinal')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 143, in <module>
    main(args)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 135, in main
    centroids = run_kmeans(annotation_dims, num_anchors)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 73, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 73, in <listcomp>
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]

  File "C:\ProgramData\Anaconda3\lib\random.py", line 188, in randrange
    raise ValueError("empty range for randrange()")

ValueError: empty range for randrange()

runfile('D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py', wdir='D:/My Data/My Work/GP/code/CodeFinalFinal')
Reloaded modules: preprocessing, utilss
Taher1 0
(0,)
Traceback (most recent call last):

  File "<ipython-input-41-43a4c72b639b>", line 1, in <module>
    runfile('D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py', wdir='D:/My Data/My Work/GP/code/CodeFinalFinal')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 143, in <module>
    main(args)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 135, in main
    centroids = run_kmeans(annotation_dims, num_anchors)

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 73, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]

  File "D:/My Data/My Work/GP/code/CodeFinalFinal/gen_anchors.py", line 73, in <listcomp>
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]

  File "C:\ProgramData\Anaconda3\lib\random.py", line 188, in randrange
    raise ValueError("empty range for randrange()")

ValueError: empty range for randrange()

how i can fix it  ?

**Comment by ogbanugot** [comment]
when i use the -a option and pass an integer like this 
-a 10
i get 
File "gen_anchors.py", line 71, in run_kmeans
    old_distances = np.zeros((ann_num, anchor_num))
TypeError: 'str' object cannot be interpreted as an integer
Any help?
@RichardSieg @Spider95

**Comment by rodrigo2019** [comment]
change this
```
argparser.add_argument(
    '-a',
    '--anchors',
    default=5,
    help='number of anchors to use')
```

to this:
```
argparser.add_argument(
    '-a',
    '--anchors',
    default=5,
    help='number of anchors to use',
    type=int)
```

**Comment by ogbanugot** [comment]
Tried that and now i'm getting this:

Traceback (most recent call last):
  File "gen_anchors.py", line 138, in <module>
    main(args)
  File "gen_anchors.py", line 130, in main
    centroids = run_kmeans(annotation_dims, num_anchors)
  File "gen_anchors.py", line 74, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "gen_anchors.py", line 74, in <listcomp>
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "/home/ugot/anaconda3/lib/python3.6/random.py", line 189, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()

**Comment by rodrigo2019** [comment]
Sorry, I couldn't replicate your error

**Comment by LucasVandroux** [comment]
@ogbanugot I had a similar error and it was because I was not able to extract any annotations from the .xml files due to the fact the classes I put in my config.json file didn't correspond to the ones in the .xml files. I hope this can help you.

**Comment by ogbanugot** [comment]
Thanks, you are right. The classes in my xml file didn't match the ones in my config.json file. but i'd point out that it was when i attempted to train, that the class mismatch error was highlighted. So now that i fixed the classes in my .xml file, the get_anchors works now.
