### ISSUE TITLE
Invalid File Name - end of Epoch 1

### ISSUE THREAD

**Issue by IMABUNNEH** [experiencor/keras-yolo2#233]
Hi,

After Epoch 1 training, I get the following output + error

```
Epoch 00001: val_loss improved from inf to 10.06703, saving model to 
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 97, in _main_
    debug              = config['train']['debug'])
  File "/Users/myuser/Desktop/git_repo/keras-yolo2/frontend.py", line 336, in train
    max_queue_size   = 8)      
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/engine/training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/callbacks.py", line 447, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/engine/topology.py", line 2580, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/keras/models.py", line 106, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/myuser/.virtualenvs/cv/lib/python2.7/site-packages/h5py/_hl/files.py", line 105, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
ValueError: Invalid file name (invalid file name)
```

I can't find anything via previous issues or google that is addressing the issue, any thoughts possibly? Much appreciated.

**Comment by IMABUNNEH** [comment]
I did not. Now I feel like an idiot. Thanks I'll try that!
