### ISSUE TITLE
Yolo is not able to load pre-trained weights file

### ISSUE THREAD

**Issue by alexander-hamme** [experiencor/keras-yolo2#234]
Hello, I'm trying to train yolo on my own dataset for tadpole detection, but it can't seem to load the weights  that I specify in the config.json file. 

I tried using the "Full Yolo" architecture paired with the full_yolo_backend.h5 file, and now also tried "Tiny Yolo" with the tiny_yolo_backend.h5 file, neither worked.

The error I get is always some variation of:

`ValueError: You are trying to load a weight file containing 16 layers into a model with 2 layers.`

___________________________________________________________________________________
`('Loading pre-trained weights in', u'/home/ah2166/Documents/sproj/keras-yolo2/tiny_yolo_backend.h5')
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    _main_(args)
  File "train.py", line 81, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/ah2166/Documents/sproj/keras-yolo2/frontend.py", line 243, in load_weights
    self.model.load_weights(weight_path)
  File "/home/ah2166/.virtualenvs/opencv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/ah2166/.virtualenvs/opencv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 3354, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 16 layers into a model with 2 layers.`

Any advice on how I might resolve this and get it to load the weights file? Thanks!

**Comment by RichardSieg** [comment]
Hey,

so there's a difference in the models used and the pretrained weights. 

On the one hand, you have the weights for the backend that is used (e.g. full yolo or tiny yolo). The path to their weight file is hard coded into `backend.py`. In order to load these weights you need to download them (read the README) and put them into your yolo folder, so the backend script can find it.

On the other hand, you have weights for the **whole** model used, i.e., the backend plus some additional conv layers for the box detection (the backend is a classifier). In your config, you can specify a path to weights for that whole model. This is useful if you did some epochs of warmup training and want to load the weights from this warmup training as a start for your proper training.

**Comment by alexander-hamme** [comment]
As far as I can tell, what I currently have in the yolo root folder for `backend.py` to find are the backend files, which I downloaded from the link in the README. 

So are you suggesting that I download the full weights files, instead of just the backend weights? 

If so, should I get the weights from this link in the README?

"The link to the pretrained weights for the whole model (both frontend and backend) of the raccoon detector can be downloaded at: [(https://1drv.ms/f/s!ApLdDEW3ut5feoZAEUwmSMYdPlY)]"  ?

Because I was under the impression that these would already be trained for Raccoons, but I guess if they're going to be retrained for my dataset that would make sense, considering that this is transfer learning after all.

**Comment by RichardSieg** [comment]
Well it depends on what you would like to train. If it looks similar to raccoons (and has only a single label!) you might can use these weights. Otherwise I would suggest you just leave this field blank or you do some epochs of warmup training, save the weights (with the `saved_weights_name` field) into some file like `blabla_warm.h5` and load it (with the `pretrained_weights` field) for your proper training.

**Comment by alexander-hamme** [comment]
Thanks, doing that made it train successfully.

The issue now is that it doesn't detect anything, but I'm guessing that is either an indication that my dataset is not robust enough or I need to mess around with the network configurations...

**Comment by awesomeaku** [comment]
> As far as I can tell, what I currently have in the yolo root folder for `backend.py` to find are the backend files, which I downloaded from the link in the README.
> 
> So are you suggesting that I download the full weights files, instead of just the backend weights?
> 
> If so, I'm assuming I should get the weights from [this link](https://1drv.ms/f/s!ApLdDEW3ut5feoZAEUwmSMYdPlY) in the README, which is the link right after this:
> 
> `The link to the pretrained weights for the whole model (both frontend and backend) of the raccoon detector can be downloaded at: `
> 
> Because I was under the impression that these would already be trained for Raccoons, but I guess if they're going to be retrained for my dataset anyway that would make sense, this is transfer learning after all.

can anyone please share the frontend and backend pretained weights as it is not available now in the link mentioned above

**Comment by rodrigo2019** [comment]
https://github.com/rodrigo2019/keras_yolo2/releases
