### ISSUE TITLE
AttributeError when running detection

### ISSUE THREAD

**Issue by IMABUNNEH** [experiencor/keras-yolo2#238]
All references to this error message I've seen are related to training. Training went fine however I'm now getting the following error when attempting to predict:

```
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "predict.py", line 96, in <module>
    _main_(args)
  File "predict.py", line 87, in _main_
    boxes = yolo.predict(image)
  File "/Users/myusername/Desktop/git_repo/keras-yolo2/frontend.py", line 460, in predict
    image_h, image_w, _ = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

I've checked the filepath to the image I want to predict is correct, tried including and excluding the file extension too. I know on training this is related to image paths not being defined correctly in the xml, but as training was successful and this is on attempting to predict... any help? Much appreciated.

**Comment by IMABUNNEH** [comment]
Never mind, this was an issue with the training command.
