### ISSUE TITLE
raccoon detection accuracy

### ISSUE THREAD

**Issue by pure-water** [experiencor/keras-yolo2#246]
Hi  
  I played around the raccon a bit.  I found some false positive case. Any chance we can improve this false positive case？

![raccoon_test_05_detected](https://user-images.githubusercontent.com/2059536/38774857-6b7ff82e-4069-11e8-9657-6f6bd5d4a5c9.jpg)

![raccoon_test_07_detected](https://user-images.githubusercontent.com/2059536/38774858-72bbe6e8-4069-11e8-9fc1-793d67b26159.jpg)

**Comment by pure-water** [comment]
I think for the negative positive, we can improve it by training a bit harder. Can we deal with the false positive more efficiently? 

![raccoon_test_09_detected](https://user-images.githubusercontent.com/2059536/38774902-50b76f9e-406a-11e8-979e-656f5ba83b92.jpg)

![raccoon_test_01_detected](https://user-images.githubusercontent.com/2059536/38774893-21559780-406a-11e8-95e6-e648f619c80e.jpg)

**Comment by bexx1963** [comment]
How many epochs did you train?

**Comment by pure-water** [comment]
I predicted it directly with the pre-trained weights (backend is mobile-net)  mobilenet_raccoon.h5 from experiencor's area. I do not know how many epoch to take to get where we are now.

Regards

**Comment by experiencor** [comment]
@pure-water This occurs to me too. To address this, you need to add images with no raccoon to the dataset, which serve as negative examples. Better with other similarly looking animals.

**Comment by bexx1963** [comment]
How did you labeled the no-raccoon images? With Bounding box or without bounding box? When you labeled it with bbox, did you placed it around the object in the picture or somewhere?

**Comment by experiencor** [comment]
just no bounding boxes

**Comment by bexx1963** [comment]
![grafik](https://user-images.githubusercontent.com/28936520/38880425-fe388fe8-4265-11e8-969a-fe5dd965c0f8.png)

Does xml file then look like this with empty <bndbox></bndbox> and class "garbage"?
train.py gives me an error

**Comment by bexx1963** [comment]
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    _main_(args)
  File "train.py", line 98, in _main_
    debug              = config['train']['debug'])
  File "/media/srv-0/abajrami/YOLOv2/frontend.py", line 383, in train
    max_queue_size   = 8) 
  File "/home/abajrami/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/abajrami/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/abajrami/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "/home/abajrami/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
StopIteration: 'xmin'

**Comment by pure-water** [comment]
A side question to @experiencor .  I am fairly new to training. I used to use dark-net native frame work for training as well which use a bit different annotation syntax (csv type more or less). Here you seem to be using XML instead.  Is this determined by Keras or a personal design choice?     I am just wondering in the machine learning training community, is there a standard training-syntax so it will save people extra from when switching frame work.

**Comment by experiencor** [comment]
You should remove tag object altogether like:

```
<annotation verified="yes">
	<folder>images</folder>
	<filename>raccoon-105.png</filename>
	<path>/Users/datitran/Desktop/raccoon/images/raccoon-105.png</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>720</width>
		<height>960</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
</annotation>
```

I think that the VOC format is most straight-forward to me: one xml annotation for one image.

**Comment by bexx1963** [comment]
When I do so and start training then we dont read the negative examples. We only read the pics which are specified in config['model']['labels'].

Due to the fact that we removed the <object> tag in the xml file for the negative examples, these pictures have no class and then the code isnt reading them.

How to deal with this?

**Comment by experiencor** [comment]
@bexx1963 You can disable the checking at line 55 of processing.py to include images with no labels. Still keep line 56.

**Comment by pure-water** [comment]
I think I have a fix. Basically I just need to scale the predicate_box back to the whole size space. 

![image](https://user-images.githubusercontent.com/2059536/39129644-95cdc9c8-473d-11e8-9d92-7297cc6715e3.png)

**Comment by experiencor** [comment]
It seems so. Can you make a PR so I can merge?

**Comment by pure-water** [comment]
@experiencor 

I make a PR request , please merge

Regards

**Comment by experiencor** [comment]
Merged. Thanks, @pure-water.

**Comment by pure-water** [comment]
@experiencor  - Just wondering for the pre-trained weight (as mobilenet) you put on the web? How many training you did to get them ?

**Comment by experiencor** [comment]
I don't remember.

**Comment by jzx-gooner** [comment]
> When I do so and start training then we dont read the negative examples. We only read the pics which are specified in config['model']['labels'].
> 
> Due to the fact that we removed the tag in the xml file for the negative examples, these pictures have no class and then the code isnt reading them.
> 
> How to deal with this?

I want to add some negative dataset to train and I got this error when i changing  
**_if len(img['object']) > -1:_**
Traceback (most recent call last): File "train.py", line 100, in <module> _main_(args) File "train.py", line 96, in _main_ debug = config['train']['debug']) File "/home/keras-yolo2/frontend.py", line 341, in train average_precisions = self.evaluate(valid_generator) File "/home/keras-yolo2/frontend.py", line 400, in evaluate all_annotations[i][label] = annotations[annotations[:, 4] == label, :4].copy() IndexError: index 4 is out of bounds for axis 1 with size 0
**what have you done to add the negative dataset?** **thank you very much**
