### ISSUE TITLE
I encountered a problem in preprocessing.py

### ISSUE THREAD

**Issue by NiFangBaAGe** [experiencor/keras-yolo2#263]
When I run gen_anchors.py or train.py, it occurs ：
Traceback (most recent call last):
  File "gen_anchors.py", line 5, in <module>
    from preprocessing import parse_annotation
  File "/home/liuweihuang/code/keras-yolo2/preprocessing.py", line 7, in <module>
    from keras.preprocessing import Sequence
ImportError: cannot import name 'Sequence‘

My version of keras is 2.1.5 and I change Sequence to sequence,
then it occurs :
Traceback (most recent call last):
  File "gen_anchors.py", line 5, in <module>
    from preprocessing import parse_annotation
  File "/home/liuweihuang/code/keras-yolo2/preprocessing.py", line 60, in <module>
    class BatchGenerator(sequence):
TypeError: module.__init__() takes at most 2 arguments (3 given)

How can I run it?

**Comment by experiencor** [comment]
Try using the latest Keras.

**Comment by wangwei420625** [comment]
![image](https://user-images.githubusercontent.com/31655266/58714226-dd546580-83f6-11e9-9296-614e034ac822.png)

**Comment by wangwei420625** [comment]
I also encountered the same problem, how should I solve it?
