### ISSUE TITLE
Problem on download pretrained weight.

### ISSUE THREAD

**Issue by HanYuanyuaner** [experiencor/keras-yolo2#264]
I can not download the pretrained weight from https://1drv.ms/f/s!ApLdDEW3ut5fec2OzK4S4RpT-SU or https://1drv.ms/f/s!ApLdDEW3ut5feoZAEUwmSMYdPlY. Can anyone share it ?

**Comment by experiencor** [comment]
Use proxysite.com

**Comment by houxy12** [comment]
proxysite.com doesn't work for me. @experiencor

**Comment by HanYuanyuaner** [comment]
It also doesn't work for me

**Comment by GitMsw** [comment]
Can share another one?  in need

**Comment by lychenpan** [comment]
Same problem for me.  It seems we need to convert the yolo2 weights on its official website to keras format.

**Comment by lychenpan** [comment]
I have transformed one yolov2.weights(without the last linear layer) to h5 file using this [script](https://github.com/allanzelener/YAD2K),  you can download it [here ](https://pan.baidu.com/s/1Ro2zM9twu18RL0X9BvILNg)

**Comment by mdawas** [comment]
I have the same problem, I can't download the pretrained weights for the whole model and I didn't find the Full_Yolo weights too!
Anyone got that problem solved?

**Comment by rodrigo2019** [comment]
https://github.com/rodrigo2019/keras-yolo2/releases

**Comment by mdawas** [comment]
@rodrigo2019 Thanks alot! it worked!

**Comment by mdawas** [comment]
@rodrigo2019  I have a problem when using the Full Yolo backend with the  weights in the mentioned repo, the training can't start and the following error is logged:

`Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 70, in _main_
    anchors             = config['model']['anchors'])
  File "/geo/home/i501245/projects/keras-yolo/keras-yolo2/frontend.py", line 48, in __init__
    self.feature_extractor = FullYoloFeature(self.input_size)
  File "/geo/home/i501245/projects/keras-yolo/keras-yolo2/backend.py", line 167, in __init__
    self.feature_extractor.load_weights(FULL_YOLO_BACKEND_PATH)
  File "/geo/home/d067913/envs/miniconda2/envs/mohammad/lib/python2.7/site-packages/keras/engine/topology.py", line 2645, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/geo/home/d067913/envs/miniconda2/envs/mohammad/lib/python2.7/site-packages/keras/engine/topology.py", line 3139, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 45 layers into a model with 44 layers.`

Have you got the same error or there is something should be modified in building the network?
