### ISSUE TITLE
Understand how to start

### ISSUE THREAD

**Issue by frasab** [experiencor/keras-yolo2#274]
Hi :)
My goal is to understand how I can apply fine tuning to such neural network, and so I want to run your code and play with it ;)
My problem is that deep learning is a new topic for my studies, so I have some problems to understand each part of your software.
I have read the YOLO paper and I have an idea about how it works.
I have prepared dataset, as you suggest in the section "Usage for python Code", but my first question is:
- Who generates annotations from images in VOC format?
Are annotations only labels for images? What is their meaning?
Once that annotations are generated, I have to generate anchors. Does your gen_anchors script updates the raw about anchors  in the conf.json file?
Thank you so much for you response!

**Comment by ManjeeraJagiri** [comment]
Hi,

**1)Who generates annotations from images in VOC format?**
A)Annotations for images are created manually using tools like labelImg (https://github.com/tzutalin/labelImg)

**2)Are annotations only labels for images.What is their meaning?**
A)Annotations are ground truth labels of the images. They have info about what all objects are present in the image `(<name>raccoon</name>)` and their bounding box coordinates relative to the image `(<bndbox>
<xmin>81</xmin>
<ymin>88</ymin>
<xmax>522</xmax>)
<ymax>408</ymax>
</bndbox>`
This info is later parsed to be used accordingly .

As the author mentioned, **copy the generated anchors printed on the terminal to the anchors setting in config.json**

**Comment by frasab** [comment]
Thank you Manjeera! You have been very clear!
Maybe you can help me once again...
When I run the script in order to generate anchors, the code produces an exception:
`FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "gen_anchors.py", line 137, in <module>
    main(args)
  File "gen_anchors.py", line 129, in main
    centroids = run_kmeans(annotation_dims, num_anchors)
  File "gen_anchors.py", line 73, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "/usr/lib/python2.7/random.py", line 193, in randrange
    raise ValueError, "empty range for randrange()"
ValueError: empty range for randrange()
`
Can you help me to understand where is the origin of the exception?
Besides, can you give me a short description of the flow of the software?
Once that I created anchors, I have to preprocess my images and so train again, in order to update my weights, and so I have to run train script? or frontend script?

However, where the author indicates his changes respect to yolo original? Where he changes and does the fine tuning?

**Comment by ManjeeraJagiri** [comment]
You have to run train.py script

In train.py, the following piece of code imports YOLO from frontend.

```
    yolo = YOLO(backend             = config['model']['backend'],
                input_size          = config['model']['input_size'], 
                labels              = config['model']['labels'], 
                max_box_per_image   = config['model']['max_box_per_image'],
                anchors             = config['model']['anchors'])

```
Let's see what happens in frontend.py. The following piece of code imports the FullYoloFeature from backend

```
elif backend == 'Full Yolo':
            self.feature_extractor = FullYoloFeature(self.input_size)
```
Let's see what happens in backend.py

The model is constructed till layer 22(including layer 22), and the weights from the original yolo are loaded in this model given by the following piece of code

```
        self.feature_extractor = Model(input_image, x)  
        self.feature_extractor.load_weights(FULL_YOLO_BACKEND_PATH)
```
Now moving back back to frontend.py, the author creates the final layer(layer 23) according to no. of classes,no. of anchors etc. He/She initializes this layer with random weights. You can see that in the below code


```
# make the object detection layer
        output = Conv2D(self.nb_box * (4 + 1 + self.nb_class), 
                        (1,1), strides=(1,1), 
                        padding='same', 
                        name='DetectionLayer', 
                        kernel_initializer='lecun_normal')(features)
        output = Reshape((self.grid_h, self.grid_w, self.nb_box, 4 + 1 + self.nb_class))(output)
        output = Lambda(lambda args: args[0])([output, self.true_boxes])

        self.model = Model([input_image, self.true_boxes], output)

        
        # initialize the weights of the detection layer
        layer = self.model.layers[-4]
        weights = layer.get_weights()

        new_kernel = np.random.normal(size=weights[0].shape)/(self.grid_h*self.grid_w)
        new_bias   = np.random.normal(size=weights[1].shape)/(self.grid_h*self.grid_w)

        layer.set_weights([new_kernel, new_bias])
```

The above layer is what is finetuned. When the Model is called, the following piece of code `features = self.feature_extractor.extract(input_image) extracts the features from the backend model(layer1-layer22) and the rest of the Model is finetuned( layer23)

Now back to train.py, the following piece of code loads weights in the frontend model(layer23) also if you have pretrained weights for it rather than initializing with random weights.


```
    if os.path.exists(config['train']['pretrained_weights']):
        print("Loading pre-trained weights in", config['train']['pretrained_weights'])
        yolo.load_weights(config['train']['pretrained_weights'])
```

This is my understanding. It is better if you go through the code and check it yourself.

**Comment by frasab** [comment]
Thank you very much!
I have tried to run the train script with pretrained weights in order to finetune the network, but it starts from the 1st epoch and seems that it repeats the training of all layers. Is it possible to finetune only some layers in the yolo net?

**Comment by ManjeeraJagiri** [comment]
1st epoch is not equivalent to 1st layer. Please google the terms, you will get a better understanding.
Like I mentioned above, layer 23 is only fine-tuned when you run the training script. The features from the previous layers are extracted and the fed into layer 23.

**Comment by frasab** [comment]
Sorry Manjeera, maybe I have been unclear! Now I understand what epoch means.
My idea of fine tuning is that I can froze some layers of the network, preserving their weights (pretrained weights in the config.json file?) and then training new layers or retraining some layers. 
When I run the train script, I expect that the input goes through all convnet in order to update only the new layer weights, but I see that there are around 50000 parameters, and so I think that the whole network is retrained. What are their goal? What am I missing? How can I check if weights are changed?
Anyway, thank you very much for your time and patience!
Best regards :)

**Comment by ManjeeraJagiri** [comment]
Your idea of fine tuning is correct. Did you check the #paramenters through model.summary(). ? 
The goal is supposedly to retrain only the final layer of the network for a new dataset. 
You can get layer weights using get_weights(). And then compare.

**Comment by frasab** [comment]
thank you! Sorry, but I have other dubts and questions :(
I have seen the parameters and I think that they are too many, but probably I'm wrong! 
My dubt is that if I want to train only the layer 23, I should have less trainable parameters. 
Furthermore, I have understood that if I want to froze some layers of a NN, I should use their flag "trainable" and pone it to "FALSE". I didn't see any piece of code that emulates this procedure.
Can you help me to understand what is their meaningful? 
For example

`Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672`

Furthermore, the output of summary function is subdivided into layer, output shape, param and connected layer.

`Layer (type)                    Output Shape         Param #     Connected to                     
===============================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
___________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 50547936    input_1[0][0]                    
___________________________________________________________________________________
DetectionLayer (Conv2D)         (None, 13, 13, 30)   30750       model_1[1][0]                    
___________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 6) 0           DetectionLayer[0][0]             
___________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0                                            
___________________________________________________________________________________
lambda_2 (Lambda)               (None, 13, 13, 5, 6) 0           reshape_1[0][0]                  
                                                                                            input_2[0][0]                    
===============================================================================`
Is model_1 the set of layers? for example, in full yolo the model is composed by 22 layers?
What is the difference between input_1 and input_2? what is the lambda2 layer? 

 (None, 13, 13, 5, 6)
What are these parameters? There is one more respect to the previous...

**Comment by rodrigo2019** [comment]
try to freeze the layers after this [line](https://github.com/experiencor/keras-yolo2/blob/master/frontend.py#L84) doing something like:

```python
for layer in self.model.layers:
    layer.trainable=False
```
model_1 is your backend defined [here](https://github.com/experiencor/keras-yolo2/blob/master/backend.py)

the diference between inputs is that one is your image and another is the ground truth boxes, this special input is used in the [custom_loss](https://github.com/experiencor/keras-yolo2/blob/master/frontend.py), and it is used just in the training, for inference this input is a dummy input
the lambda function is a way to put this special input inside the model, and make it acessible by the custom_loss function, I'm not sure about that, you can verify it comparing the outputs between the lambda layer and the reshape layer, it should be the same results.
if you have some doubt how to do that, check this [link](https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer)


` (None, 13, 13, 5, 6)` is `(batch,grid_h,grid_x,anchors,predictions bboxes + classification)`

**Comment by frasab** [comment]
thank you rodrigo!
I have tried to set the trainable flag to false how you suggest me and I see that now the number of trainable parameters is how I expect.
Anyway, can you give me an help to understand the output of the train script?
In particular, I don't understand when the output about loss function is printed... after each layer?
Furthermore, can you help me to understand some parameters of config.json file?
In particular: learning rate, object_scale, no_object_scale, coord_scale, class_scale and debug
what is the difference between epoch and warm up epoch?
Thank you for your time!
Best regards!

**Comment by rodrigo2019** [comment]
for sure, I can,

> In particular, I don't understand when the output about loss function is printed... after each layer?

Are you talking about this line?
![image](https://user-images.githubusercontent.com/8016520/39900956-bf9a270e-549b-11e8-8640-7154f5fa65ac.png)
the loss is updated after each batch

learning rate: it is the learning rate from the optimizer
this repository are using [Adam](https://github.com/experiencor/keras-yolo2/blob/master/frontend.py#L300)

from [readme.md](https://github.com/experiencor/keras-yolo2/blob/master/README.md) you can read this:

>         "object_scale":         5.0 ,           # determine how much to penalize wrong prediction of confidence of object predictors
>         "no_object_scale":      1.0,            # determine how much to penalize wrong prediction of confidence of non-object predictors
>         "coord_scale":          1.0,            # determine how much to penalize wrong position and size predictions (x, y, w, h)
>         "class_scale":          1.0,            # determine how much to penalize wrong class prediction


> what is the difference between epoch and warm up epoch?

I don't much about it, but again, in the [readme.md](https://github.com/experiencor/keras-yolo2/blob/master/README.md) says:

>         "warmup_epochs":        3,              # the number of initial epochs during which the sizes of the 5 boxes in each cell is forced to match the sizes of the 5 anchors, this trick seems to improve precision emperically

but take care with these warmup_epochs, too many on small datasets causes bad results

**Comment by frasab** [comment]
Thank you rodrigo!
Sorry, but I don't have the same your output :(
During each epoch I see this output repeatedly:

> Loss XY 	[0.0914146677]
Loss WH 	[3.45645452]
Loss Conf 	[0.00183097296]
Loss Class 	[0]
Total Loss 	[3.54970026]
Current Recall 	[0]
Average Recall 	[0]

I have understood that these values are relative to loss function, but when are computed? after a layer?

At the end of each epoch, I see this ouput:

> -5121s - loss: 10.0037 - val_loss: 10.0030
Epoch 00002: val_loss improved from 10.00391 to 10.00304, saving model to pathFile

What is the difference between loss and val_loss?

**Comment by rodrigo2019** [comment]
Ah, I got it, it is because you are with debug option activated. In config.json, change the [debug](https://github.com/experiencor/keras-yolo2/blob/master/config.json#L27) value to false, and you will get a clean view of training.
theseoutputs that you are seening is from [here](https://github.com/rodrigo2019/keras-yolo2/blob/master/frontend.py#L226) in the custom loss function

> I have understood that these values are relative to loss function, but when are computed? after a layer?

after each batch

> What is the difference between loss and val_loss?

loss is the loss in yout training dataset and val_loss is your loss in the validation dataset

> Furthermore, I have some dubts about the number of layers:

I didn't understand your question, could you provide the whole code?
model_1 is your backbone model, it can be any kind of network, for default the backbone is Full Yolo, you can set another backbend in config.json, also  this PR #281 , you can set a custom network as backend

**Comment by rodrigo2019** [comment]
Hi @mohamedabdallah1996 

First of all tiny_yolo_backend is the weights for the backend, You do not need to set this files in the config.json, the code will automatically look for this file when loads the backend.
tiny_yolo_raccon.h5 will not work, because this is the weights for the whole model, it include the weights for the last convolution that is the detection layer, this means it will just work if your model has the same amount of classe, but you don't have, raccon has 1 class and your problem has 32. So you must leave the pre trained weights field in blank, you are not going to train from scratch, because the model will load the back weights automatically.

Which backend will should choose? It depends what is important to you, speed? precision? How diversified is your dataset? how muany samples do you have? YOu need to consider all this factors
In my opnion you must test many models and compare the results.

about the nans values, looking your config.json looks you generated your owns anchors , and some anchors has value 0, this values probabily was rounded by precision. Try to exclude this anchors. And with such small anchors looks your dataset has small dimensions too, if your dataset has too much small dimension, you must train in a biggerscale, or change the backend in order to get a bigger grid, but in this case you will need train from scratch

**Comment by frasab** [comment]
Hi Rodrigo! 
I'm interested in the Full Yolo model. 
In the paper yolo9000, the authors wrote that the final model, Darknet 19, is composed by 19 convolutional layers and 5 max pooling layers (24 layers).
Instead the author of this implementation put 22 convolutional layer and 1 max pooling layer.
This is my dubt. I think that something escapes me.
Another question is about the pretrained weight... I try to use the full_yolo_backend version and not the raccon version, because I'm interested on the original model.
When I load the raccon version, all work fine.
When I load the backend version, I have this problem:

> ValueError: You are trying to load a weight file containing 44 layers into a model with 2 layers.

Can you help me to understand how to solve these problems?
thank you very much!

**Comment by rodrigo2019** [comment]
[here](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-voc.cfg) is the cfg file from original yolo, and [here](https://github.com/experiencor/keras-yolo2/blob/master/backend.py#L36) is the yolo from this implementation,  if you compare both, you will realize that in this implemantations is missing one conv layer, this missing conv layer is [here](https://github.com/experiencor/keras-yolo2/blob/master/frontend.py#L63).

in this [jupyter](https://github.com/experiencor/keras-yolo2/blob/master/Yolo%20Step-by-Step.ipynb) tutorial, @experiencor uses a tools that converts the weights from original yolo, to the keras version.

About the pre trained weights, read my answer to mohamed before your comment

**Comment by frasab** [comment]
Thank you very much!
In your previous answer to mohamed, you suggest him to modify the object scale in case of small images in the dataset. I have small images and smaller bounding boxes, in order to change the scale I have to modify "object_scale" and "coord_scale" in config.json?

I have another question: what means each value of the anchors array? In the paper they speak that the network predicts 5 bounding boxes for each cell of the feature map and then predicts 5 coordinates for each bounding box (tx, ty, tw, th, to). I see 10 elements in the result array, what are they?

**Comment by rodrigo2019** [comment]
you got six layers because inside this model has another model that has almost all layers:

![image](https://user-images.githubusercontent.com/8016520/40845318-bab38e2c-658c-11e8-9649-e8c2cfdb1f68.png)
Why your summary has different names than mine? Because I changed it in my [fork](https://github.com/rodrigo2019/keras-yolo2)

in model.layers[1] in this image has a Sequential model that is the backend, to check this model you can try `model.layers[1].summary()` or `model.layers[1].layers` to check the amount of layers
> In your previous answer to mohamed, you suggest him to modify the object scale in case of small images in the dataset. I have small images and smaller bounding boxes, in order to change the scale I have to modify "object_scale" and "coord_scale" in config.json?

from readme.md:
>     "object_scale":         5.0 ,           # determine how much to penalize wrong prediction of confidence of object predictors
>     "no_object_scale":      1.0,            # determine how much to penalize wrong prediction of confidence of non-object predictors
>     "coord_scale":          1.0,            # determine how much to penalize wrong position and size predictions (x, y, w, h)
>     "class_scale":          1.0,            # determine how much to penalize wrong class prediction

>  I see 10 elements in the result array, what are they?

that is the values for w and h to each anchor, so if you have 10 values, actually you have 5 anchors
take a look [here](https://mlblr.com/includes/mlai/index.html#yolov2) for a good explanation about these anchors

**Comment by frasab** [comment]
ooooh thank you! *_*
For the last question, do you know other sources where I can analyze the evaluation methods in the machine learning? I would like to know what is the best result for the mAP value, how I can evaluate it and if there is another kind of evaluation.
Sorry for my inexperience. I'm self-taught in the machine learning field.
thank you in advance

**Comment by rodrigo2019** [comment]
I dont know, sorry. what I learned was reading papers such as faster rcnn, retinanet, yolo, ssd, etc

**Comment by Akashpanchal95** [comment]
@rodrigo2019 & @frasab & @mohamedabdallah1996. Thank you for the conversion. It has cleared many of my doubts. I have the small question regarding the training from scratch.

> "As you mention @mohamedabdallah1996 
> if your images from your dataset has too much small dimension, you must train in a bigger scale, or change the backend in order to get a bigger grid, but in this case you will need train from scratch."

Could you please guide me what parameter should I change in order to train smaller object like 'Polythene or Pendrive' from scratch.
