### ISSUE TITLE
Unable to reduce number of anchor boxes

### ISSUE THREAD

**Issue by jerinka** [experiencor/keras-yolo2#301]
To reduce anchorboxes from five to one, i tried editing config file, but training is throwing error. Also i am not able to load back end weights alone, when given backend weight file name in config, i was throwing error.

**Comment by rodrigo2019** [comment]
What kind of error? here it is working for a single anchor
The pre trained weights path in config file it is for the whole model, not just for the backend

**Comment by jerinka** [comment]
Oops i forgot to say thank you, thank you for providing this awesome project!!
 When i made number of anchors to one as shown below, i got error that is pasted below 
##########################################
{
    "model" : {
        "backend":              "MobileNet",
        "input_size":           416,
        "anchors":              [0.57273],
        "max_box_per_image":    1,
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "F:/basic_codes/keras-yolo2-master/train_image_folder/",
        "train_annot_folder":   "F:/basic_codes/keras-yolo2-master/train_annot_folder/",

        "train_times":          8,
        "pretrained_weights":   "mobilenet_raccoon.h5",
        "batch_size":           3,
        "learning_rate":        1e-4,
        "nb_epochs":            1,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "mobilenet_yolo_saved.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}
###############################################

I got this error,

######################################################
(13, 13)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 3228864     input_1[0][0]                    
__________________________________________________________________________________________________
DetectionLayer (Conv2D)         (None, 13, 13, 0)    0           model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 0, 6) 0           DetectionLayer[0][0]             
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 1, 4 0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 13, 13, 0, 6) 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 3,228,864
Trainable params: 3,206,976
Non-trainable params: 21,888
Loading pre-trained weights in mobilenet_raccoon.h5
Traceback (most recent call last):
  File "F:/basic_codes/keras-yolo2-master/train.py", line 104, in <module>
    _main_(args)
  File "F:/basic_codes/keras-yolo2-master/train.py", line 81, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "F:\basic_codes\keras-yolo2-master\frontend.py", line 243, in load_weights
    self.model.load_weights(weight_path)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\topology.py", line 3382, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2373, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (30, 1024, 1, 1) for Tensor 'Placeholder_135:0', which has shape '(1, 1, 1024, 0)'

Process finished with exit code 1
##############################

Is is possible to just use pretrained weight of backend and train front end from scratch (when anchors are reduced)? I am trying to do character recognition using yolo and it wont require multiple anchors i believe.

**Comment by bexx1963** [comment]
You have to define one anchor box by two numbers for width and height.
For example
{
"model" : {
"backend": "MobileNet",
"input_size": 416,
**"anchors": [0.57273, 0.43243],**
"max_box_per_image": 1,
"labels": ["raccoon"]
},

**Comment by jerinka** [comment]
Edited config as you suggested, but while training its showing same error as above,  i am using mobilenet_backend.h5 pretrained weights

###
{
    "model" : {
    "backend": "MobileNet",
    "input_size": 416,
    "anchors": [0.57273, 0.43243],
    "max_box_per_image": 1,
    "labels": ["raccoon"]
    },

    "train": {
        "train_image_folder":   "F:/basic_codes/keras-yolo2-master/train_image_folder/",
        "train_annot_folder":   "F:/basic_codes/keras-yolo2-master/train_annot_folder/",

        "train_times":          8,
        "pretrained_weights":   "mobilenet_raccoon.h5",
        "batch_size":           3,
        "learning_rate":        1e-4,
        "nb_epochs":            1,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "mobilenet_yolo_saved.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

###
error
###
(13, 13)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 3228864     input_1[0][0]                    
__________________________________________________________________________________________________
DetectionLayer (Conv2D)         (None, 13, 13, 6)    6150        model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 1, 6) 0           DetectionLayer[0][0]             
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 1, 4 0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 13, 13, 1, 6) 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 3,235,014
Trainable params: 3,213,126
Non-trainable params: 21,888
__________________________________________________________________________________________________
Loading pre-trained weights in mobilenet_raccoon.h5
Traceback (most recent call last):
  File "F:/basic_codes/keras-yolo2-master/train.py", line 104, in <module>
    _main_(args)
  File "F:/basic_codes/keras-yolo2-master/train.py", line 81, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "F:\basic_codes\keras-yolo2-master\frontend.py", line 243, in load_weights
    self.model.load_weights(weight_path)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\topology.py", line 3382, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2373, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (30, 1024, 1, 1) for Tensor 'Placeholder_135:0', which has shape '(1, 1, 1024, 6)'

Process finished with exit code 1
###

**Comment by rodrigo2019** [comment]
@jerinka  I think you found a bug, I got the same error for the specific pre trained weights, this error looks like that pre trained model has 25 classes, and you are going to train in just 1 class
Did you tested with another backends?

But @bexx1963  is also correct, your anchor was wrong.

`"max_box_per_image": 1` is not a good idea, this means that your model will train just 1 object per image, so if in the image has 2 raccoons, your training will going to see just one, and the another one will be a background, it will degrade your training

**Comment by athulpa** [comment]
I had the same two issues on my first day using this program. 

1) Soln to the backend Weights Issue:
The 'pretrained weights' field is only if you want to load fully trained weights (backend+frontend) and then start your training from there. If you want to train frontend from scratch, then leave this field blank. Then make sure the backend weights file (such as tiny_yolo_backend.h5) is present in the main directory of the downloaded repo. That seems to take care of that issue.

2) Regarding the Anchor Boxes Issue: 
I wanted to have no anchor boxes at all to do my training. Is that not possible? Can't I just disable this feature? 
Setting anchor_boxes = [] in config.json produces the error: 'Tensor' object has no attribute 'assign'
(as described by RyanCodes44 in Issue 228).
