### ISSUE TITLE
Training raccoon dataset problem

### ISSUE THREAD

**Issue by hamburgerBear** [experiencor/keras-yolo2#321]
Hi,
thanks of your code,
but i have a problem when i to training raccoon dataset 

Using TensorFlow backend.
('Seen labels:\t', {'raccoon': 217})
('Given labels:\t', [u'raccoon'])
('Overlap labels:\t', set(['raccoon']))
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 66, in _main_
    yolo = YOLO(backend             = config['model']['backend'],
KeyError: 'backend'

**Comment by fabiomazzarella** [comment]
Hi @hamburgerBear ,

Please, could you post the file config.json you are using?

**Comment by hamburgerBear** [comment]
sorry, i don't know how to reply your email "email address is error", very glad can to receive your email, thank you and my config.json is:

{
    "model" : {
        "architecture":         "Full Yolo",   
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/home/gaojie/keras_yolo2/raccoon_dataset/raccoon_dataset/images/",
        "train_annot_folder":   "/home/gaojie/keras_yolo2/raccoon_dataset/raccoon_dataset/annotations/",      
          
        "train_times":          10,             
        "pretrained_weights":   "",            
        "batch_size":           16,             
        "learning_rate":        1e-4,          
        "nb_epoch":             50,             
        "warmup_epochs":        3,              

        "object_scale":         5.0 ,           
        "no_object_scale":      1.0,           
        "coord_scale":          1.0,           
        "class_scale":          1.0,           

        "debug":                true           
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

**Comment by fabiomazzarella** [comment]
The error pops up because the train.py looks for the field config[model][backend] that does not exist in your file. In the config.json, you should change the "architecture" field into "backend".

**Comment by hamburgerBear** [comment]
thank you , 
but i don't how to do ,i just a new ,don't understand, thank you angin

**Comment by fabiomazzarella** [comment]
Please, change the **model** section of your config.json as follows:

"model" : {
"backend": "Full Yolo",
"input_size": 416,
"anchors": [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
"max_box_per_image": 10,
"labels": ["raccoon"],
}
