### ISSUE TITLE
Unable to convert keras-yolo2 model to CoreML due to lambda layer

### ISSUE THREAD

**Issue by visionscaper** [experiencor/keras-yolo2#361]
Hello!

Your Keras Yolo2 model contains a lambda layer that doesn't seem to do much:

```
output = Lambda(lambda args: args[0])([output, self.true_boxes])
```

*Why is it in there?* This layer stops me from converting the model in to a CoreML model ...

**Comment by rodrigo2019** [comment]
the purpose of the lambda layer is when it is training, for inference you can remove it

**Comment by visionscaper** [comment]
@anuar12 I didn't look at onnxmltools, but you need to make an "inference" version of the YOLO model that doesn't use the true_boxes not the Lambda layer.

Than, if you use Tiny Yolo as backend you can convert the model to a CoreML model. For the lambda layer in other backends you need to make a custom CoreML layer, but I haven't looked in to that yet.

**Comment by rodrigo2019** [comment]
@visionscaper, the function to get the inference model you can get it [here](https://github.com/rodrigo2019/keras-yolo2/blob/master/frontend.py#L384)

**Comment by anuar12** [comment]
@visionscaper and @rodrigo2019 thank you for a quick reply! Really appreciate.
I just tried your suggestion. Unfortunately got the next error:
`
Traceback (most recent call last):
  File "predict.py", line 179, in <module>
    _main_(args)
  File "predict.py", line 85, in _main_
    onnx_model = onnxmltools.convert_keras(yolo_inf)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/main.py", line 38, in convert_keras
    target_opset, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/keras/convert.py", line 43, in convert
    topology.compile()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 624, in compile
    self._infer_all_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 500, in _infer_all_types
    operator.infer_types()
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_topology.py", line 101, in infer_types
    _registration.get_shape_calculator(self.type)(self)
  File "/home/cheng/miniconda2/envs/tensorflow/lib/python2.7/site-packages/onnxmltools/convert/common/_registration.py", line 68, in get_shape_calculator
    raise ValueError('Unsupported shape calculation for operator %s' % operator_name)
ValueError: Unsupported shape calculation for operator identity
`

I think it's just because there is Lambda layer in `backend.py` in FullYolo. There isn't one in the Tiny YOLO =).
